# Generated by Django 4.2.3 on 2023-09-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rename_teacher_studentclassroom_responsible_teacher'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='classroom',
            field=models.ManyToManyField(to='student.studentclassroom'),
        ),
    ]
