# Generated by Django 4.2.3 on 2023-09-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacherprofile_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='classroom',
            new_name='classrooms',
        ),
    ]
