# Generated by Django 4.2.3 on 2023-09-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_classroom_teacherprofile_classrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='classrooms',
        ),
    ]
