# Generated by Django 4.2.3 on 2023-10-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_studentclassroom_slug'),
        ('teacher', '0004_remove_teacherprofile_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentclassroom'),
        ),
    ]
