# Generated by Django 4.2.3 on 2023-11-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_profile_image_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userslug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
