# Generated by Django 4.2.3 on 2023-10-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='blog.tag'),
        ),
    ]
