"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!2%hj727*@-2y*2@^z%(!qty8$toiah!67m=hk_%am0%)9hdzw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Do it with, for example Ipv4 is x and you have to go this url x:8000
ALLOWED_HOSTS = [
    '127.0.0.1',
    '192.168.1.41',
    '10.26.250.109',  # University library kbu_C
    '10.25.129.122',
]


# Application definition

BASE_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PART_APPS = [
    'crispy_forms',
    'crispy_bootstrap5',
    'autoslug',
    'easy_thumbnails',
]

MY_APPS = [
    'page',
    'user_profile',
    'account',
    'student',
    'teacher',
    'classroom',
    'blog',
    'assignment',
    'attendance',
]

INSTALLED_APPS = BASE_APPS + THIRD_PART_APPS + MY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.global_context_processor.profile_image',
                'config.global_context_processor.completion_percentage',
                'config.global_context_processor.blog_profile',
                # 'config.global_context_processor.StudentClassroom',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Media işlemleri
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media_files'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static_files',
]
ADMINS = [
    ('KEREM CAN', 'django@django.com'),
]

# Assignment settings
ALLOWED_FILE_TYPES = ['.pdf', '.doc', '.docx']


# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTH_USER_MODEL = 'account.User'
# Allow only staff and superusers to login to the admin page

LOGIN_ADMIN_RESTRICTED = True


# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

THUMBNAIL_ALIASES = {
    '': {
        'avatar': {'size': (30, 30), 'crop': True},
        'avatar2': {'size': (100, 100), 'crop': True},
        'profile': {'size': (200, 200), 'crop': True},
        'thumbnail': {'size': (400, 300), 'crop': True},
        'page': {'size': (1000, 250), 'crop': True},
        'cover_image': {'size': (730, 350), 'crop': True}
    },
}

# YAPILMASI DÜŞÜNÜNLER:
# TODO: user_profile appine profile işlemleri aktar!! ve bunu #2Ecommerce->Customer Details gibi yapabilirsin
# TODO: Teacher için öğrenciyi takip etme
# DONE: öğretmenlerin öğrencilerini görme, bunun çin student profiline gitmeyecek, ayrı bir liste oluşturup orada gösterip öyle çekmemiz gerekiyor https://twitter.com/html5css3_dv/status/1695199371896184939?t=ntiUELfq3U3goBhQAB5r4w&s=08
# bunu yaparken bir buton koy carcatlog projesindeki gibi bir modal açılsın öyle görsün öğrenci hakkındaki detayları öğretmen !! Öğrenci profili gibi değil! Metronic de vardı bir yerde!!

# DONE: Öğrenci ve Teacher için bilgilerini güncelleme

# TODO: Öğrenci için öğretmen tarafından ödevlendirme yapabilmeli ve bunu student dashboardda gösterilmeli
# TODO: Öğretmenler için quiz app yapıp quiz puanlarını öğrenci için girilmeli
# TODO: Top recent gibi en iyi öğrecileri quiz puanları ve ödev teslim sayısını dikkate alarak kupalara göre ayarlanabilir. Top recent olarak göster ve öğrenci kendi profilinde kupasını görsün.


# TODO: Rehber öğretmen öğrencilere randevu verebilsin görüşme için

# TODO: Öğrenciler ve öğretmenler için bir todo app gibi bir şey yapabilirsin!!

# TODO: Kullanıcı online (django-online-users 0.1)
# TODO: Kullanıcıya mesaj gönderme (django-messages 0.6.0)
# TODO: Kullanıcıya bildirim gönderme (django-notifications-hq 1.5.0)

# DONE: Telefon numarası teacher ya da parent tarafından onaylanması

# DONE: Öğrenciler için blog sistemi olabilir #Social->Feeds  # https://twitter.com/html5css3_dv/status/1695199371896184939?t=ntiUELfq3U3goBhQAB5r4w&s=08 bunu da kullanabirsin.


# TODO: Öğrenciler için oyunlar vs olabilir.   https://twitter.com/html5css3_dv/status/1695481194295734280?t=rEd-MhQkpNf4QhJTLAf-Hw&s=08
# TODO: Öğrenciler için devamsızlık bilgisi eklenecek ve bu devamsızlık bilgisi öğretmenler tarafından girecek
# TODO: Öğretmen ders programını girmeli, her öğretmen kendi branşının ders programını girecek ve ders programını gösterirken sınıfa göre ayarlamak gerekiyor.

# DONE: Öğretmen öğrenciyi sınıfa atağı zaman öğrenci dashboardda 5-A sınıfına kayıtlı olduğunu göremiyor

# Yapılma Aşamasında:
# DONE: Teacher profile edit
# DONE: Create timetable for teacher
# DONE: Teacher atama yapabiliyor ama misal yanlış ya da eksik girdi onu düzeltmesi gerekiyor.(add student to classroom-edit )
# TODO: Telefon numarası onaylama yapıldı ama telefon numarası olmadığı zamanda onaylıyor ve tel öğrenci tarafından girildiği zaman onaylanmış şekliyle geliyor.
# DONE: öğretmenlerin öğrencilerini görme, bunun çin student profiline gitmeyecek, ayrı bir liste oluşturup orada gösterip öyle çekmemiz gerekiyor https://twitter.com/html5css3_dv/status/1695199371896184939?t=ntiUELfq3U3goBhQAB5r4w&s=08
# bunu yaparken bir buton koy carcatlog projesindeki gibi bir modal açılsın öyle görsün öğrenci hakkındaki detayları öğretmen !! Öğrenci profili gibi değil! Metronic de vardı bir yerde!!

# Version 2 için yapılacaklar :
# TODO: Yapay zeka işin içi egiriş olmuş olacak ve fotoğraf yükleme için araştırma yap!!
# TODO: AI asistant yapılmalı!!
