# Generated by Django 4.2.3 on 2023-08-27 18:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
    ]
