# Generated by Django 4.2.3 on 2023-08-14 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
