# Generated by Django 4.2.3 on 2023-08-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_attendancerecord_alter_studentprofile_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassroom',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
