# Generated by Django 4.2.3 on 2023-08-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
