# Generated by Django 4.2.3 on 2023-08-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentclassroom_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='classroom',
        ),
    ]
