# Generated by Django 4.2.3 on 2023-08-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studentgrade_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassroom',
            name='attendance_records',
        ),
        migrations.RemoveField(
            model_name='studentclassroom',
            name='student',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='attendance_records',
            field=models.ManyToManyField(blank=True, null=True, to='student.attendancerecord'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentclassroom'),
        ),
    ]
