# Generated by Django 4.2.3 on 2023-08-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0006_remove_studentclassroom_attendance_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassroom',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherprofile'),
        ),
    ]
