# Generated by Django 4.2.3 on 2023-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentprofile_address_studentprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
