# Generated by Django 4.2.3 on 2023-08-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentclassroom_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclassroom',
            old_name='student',
            new_name='teacher',
        ),
    ]
