# Generated by Django 4.2.3 on 2023-09-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_classroomstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassroomStudent',
        ),
    ]
