# Generated by Django 4.2.3 on 2023-09-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_delete_classroomstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassroom',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='student.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
    ]
