# Generated by Django 4.2.3 on 2023-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_studentclassroom_student_alter_studentgrade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclassroom',
            name='student',
        ),
        migrations.AddField(
            model_name='studentclassroom',
            name='students',
            field=models.ManyToManyField(related_name='classrooms', to='student.studentprofile'),
        ),
    ]
