# Generated by Django 4.2.3 on 2023-09-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_remove_studentprofile_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentclassroom'),
        ),
    ]
