# Generated by Django 4.2.3 on 2023-09-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studentprofile_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number_active',
            field=models.BooleanField(default=False),
        ),
    ]
