# Generated by Django 4.2.3 on 2024-02-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_studentclassroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='notes',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('I', 'Illness'), ('L', 'Late'), ('A', 'Absent')], max_length=1),
        ),
    ]
