# Generated by Django 4.2.3 on 2023-12-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_remove_useranswer_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
