# Generated by Django 4.2.3 on 2023-12-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_question_is_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_true',
        ),
    ]
