# Generated by Django 4.2.3 on 2023-12-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_studentclassroom_slug'),
        ('assignment', '0005_remove_question_is_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='assignment.choice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='assignment.question'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('question', 'student')},
        ),
    ]
