# Generated by Django 4.2.3 on 2024-02-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_quiz_status_alter_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
