# Generated by Django 4.2.3 on 2024-02-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_question_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
    ]
