# Generated by Django 4.2.3 on 2024-02-16 17:23

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_uploadedsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedsolution',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[config.validators.validate_file_extension]),
        ),
    ]
